export const DEFAULTS = {
  documentNumber: "015/EPMSS-CMA/2026-27",
  agreementDate: "DD-MM-YYYY",
  clientCompanyName: "(Your Company Name)",
  clientAddress: "(Address)",
  serviceChargePercent: "___",
  gstApplicable: true,
  lockInDays: 90,
  paymentDueDays: 7,
  coolingPeriodMonths: 6,
  confirmationDays: 30,
  contractYears: 3,
  noticeDays: 30,
  arbitrationCity: "Guwahati",
  directorName: "Dangshawapipa Angrung",
};
