export const Job_posting_elements = [
  {
    id1: "location",
    label1: "Location",
    placeholder1: "e.g. Remote Mumbai",
    type1: "text",
    id2: "contract type",
    label2: "Contract Type",
    placeholder2: "Full-time",
    type2: "text",
  },
  {
    id1: "current ctc",
    label1: "Current CTC",
    placeholder1: "e.g. ₹12L - ₹18L per annum",
    type1: "text",
    id2: "experience required",
    label2: "Experience Required",
    placeholder2: "e.g. 5+ Years",
    type2: "text",
  },
  {
    id1: "max applications",
    label1: "Max Applications",
    placeholder1: "e.g. 100",
    type1: "text",
    id2: "application deadline",
    label2: "Application Deadline",
    placeholder2: "mm/dd/yyyy",
    type2: "date",
  },
];
